[features]
seeds = false
skip-lint = false
[programs.devnet]
calculator = "3E7U3DA7oLxDS4LN7fVpLfouuYka4jSuoq2a4pdLkVux"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/mateo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"